import { z } from 'zod'

export const MainZarplataFormSchema = z.object({
  kartochka: z.string(),
  rayon: z.string(),
  vacantId: z.number(),
  fio: z.string(),
  spravochikZarplataZvanieId: z.number(),
  xarbiy: z.boolean(),
  ostanovitRaschet: z.boolean(),
  raschetSchet: z.string(),
  fioDop: z.string(),
  inn: z.string(),
  bank: z.string(),
  dateBirth: z.string(),
  inps: z.string(),
  spravochnikZarplataGrafikRabotiId: z.number(),
  spravochnikSostavId: z.number(),
  stavka: z.string(),
  nachaloSlujbi: z.string(),
  visNa1Year: z.number(),
  month1: z.number(),
  day1: z.number(),
  itogo: z.number(),
  workplaceId: z.number(),
  doljnostName: z.string(),
  doljnostPrikazNum: z.string(),
  doljnostPrikazDate: z.string(),
  spravochnikZarplataIstochnikFinanceId: z.number()
})
export type MainZarplataFormValues = z.infer<typeof MainZarplataFormSchema>

export const defaultValues: MainZarplataFormValues = {
  kartochka: '',
  rayon: '',
  vacantId: 0,
  fio: '',
  spravochikZarplataZvanieId: 0,
  xarbiy: false,
  ostanovitRaschet: false,
  raschetSchet: '',
  fioDop: '',
  inn: '',
  bank: '',
  dateBirth: '',
  inps: '',
  spravochnikZarplataGrafikRabotiId: 0,
  spravochnikSostavId: 0,
  stavka: '',
  nachaloSlujbi: '',
  visNa1Year: 0,
  month1: 0,
  day1: 0,
  itogo: 0,
  workplaceId: 0,
  doljnostName: '',
  doljnostPrikazNum: '',
  doljnostPrikazDate: '',
  spravochnikZarplataIstochnikFinanceId: 0
}
