export interface SoliqOrganization {
  name: string
  inn: string
  mfo: string
  account_number: string
  okonx: string
  meta: {
    company: {
      name: string
      shortName: string
      opf: number
      kfs: number
      tin: string
      oked: string
      soogu: string
      sooguRegistrator: string
      registrationDate: string
      registrationNumber: string
      reregistrationDate: string
      status: number
      statusUpdated: string
      taxStatus: any
      liquidationDate: any
      liquidationReason: any
      suspensionDate: any
      suspensionReason: any
      taxMode: number
      vatNumber: number
      vatRegistrationDate: any
      taxpayerType: number
      businessType: number
      businessFund: number
      businessStructure: number
      businessFundCurrency: string
      createdSysDate: string
      updatedSysDate: string
      taxModeBeginDate: any
      taxModeEndDate: any
      activityTypes: any
    }
    companyBillingAddress: {
      countryCode: number
      sectorCode: number
      villageCode: string
      streetName: string
      house: any
      flat: any
      soato: number
      cadastreNumber: any
      postcode: string
    }
    companyShippingAddresses: Array<{
      countryCode: number
      sectorCode: number
      villageCode: string
      streetName: string
      house: any
      flat: any
      soato: number
      cadastreNumber: any
      postcode: any
    }>
    companyExtraInfo: {
      companyExtraInfoId: any
      avgNumberEmployees: number
      monthlyNumberEmployees: any
    }
    director: {
      lastName: string
      firstName: string
      middleName: string
      gender: number
      nationality: string
      citizenship: string
      passportSeries: string
      passportNumber: string
      pinfl: string
      tin: string
      birthDate: any
      individualId: any
      countryCode: string
    }
    directorAddress: {
      countryCode: number
      sectorCode: number
      villageCode: string
      streetName: string
      house: any
      flat: any
      soato: number
      cadastreNumber: string
      postcode: any
    }
    directorContact: {
      phone: string
      email: any
    }
    accountant: {
      lastName: string
      firstName: string
      middleName: string
      gender: any
      nationality: any
      citizenship: any
      passportSeries: string
      passportNumber: string
      pinfl: string
      tin: string
      birthDate: any
      individualId: any
      countryCode: string
    }
    accountantAddress: {
      countryCode: number
      sectorCode: number
      villageCode: string
      streetName: string
      house: any
      flat: string
      soato: number
      cadastreNumber: any
      postcode: any
    }
    accountantContact: any
    companyContact: any
    argos: any
    companyBanks: Array<{
      mfo: string
      paymentAccount: string
      status: number
      openDate: string
      closeDate: any
      attribute: number
    }>
    founders: Array<{
      founderIndividual: any
      founderLegal: {
        id: any
        tin: string
        shortName: any
        name: string
        registrationDate: any
        registrationNumber: any
        reregistrationDate: any
        businessFund: any
        businessType: any
        kfs: any
        oked: any
        opf: any
        soato: any
        soogu: any
        sooguRegistrator: any
        status: any
        statusUpdated: any
        taxMode: any
        taxpayerType: any
        vatNumber: any
        liquidationDate: any
        liquidationReason: any
        businessStructure: any
        created: any
        updated: any
        regCountry: number
        founderSharePercent: number
        founderShareSum: number
        stateTin: any
        countTotalFounders: any
        director: any
        accountant: any
        businessStructureDetail: any
        statusDetail: any
        sooguDetail: any
        activityTypes: any
        opfDetail: any
        okedDetail: any
        countryDetail: any
      }
      founderContact: any
      founderAddress: any
    }>
    companyLink: any
    companyBranches: Array<any>
  }
}
